// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module dlc_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 6
) (
    input logic clk_i,
    input logic rst_ni,
    input reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,
    // To HW
    output dlc_reg_pkg::dlc_reg2hw_t reg2hw,  // Write
    input dlc_reg_pkg::dlc_hw2reg_t hw2reg,  // Read


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import dlc_reg_pkg::*;

  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [ AW-1:0] reg_addr;
  logic [ DW-1:0] reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [ DW-1:0] reg_rdata;
  logic           reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [15:0] trans_size_qs;
  logic [15:0] trans_size_wd;
  logic trans_size_we;
  logic [15:0] curr_lvl_qs;
  logic [15:0] curr_lvl_wd;
  logic curr_lvl_we;
  logic hysteresis_en_qs;
  logic hysteresis_en_wd;
  logic hysteresis_en_we;
  logic [3:0] dlvl_log_level_width_qs;
  logic [3:0] dlvl_log_level_width_wd;
  logic dlvl_log_level_width_we;
  logic [3:0] discard_bits_qs;
  logic [3:0] discard_bits_wd;
  logic discard_bits_we;
  logic [3:0] dlvl_n_bits_qs;
  logic [3:0] dlvl_n_bits_wd;
  logic dlvl_n_bits_we;
  logic [15:0] dlvl_mask_qs;
  logic [15:0] dlvl_mask_wd;
  logic dlvl_mask_we;
  logic dlvl_format_qs;
  logic dlvl_format_wd;
  logic dlvl_format_we;
  logic [15:0] dt_mask_qs;
  logic [15:0] dt_mask_wd;
  logic dt_mask_we;
  logic bypass_qs;
  logic bypass_wd;
  logic bypass_we;

  // Register instances
  // R[trans_size]: V(False)

  prim_subreg #(
      .DW      (16),
      .SWACCESS("RW"),
      .RESVAL  (16'h0)
  ) u_trans_size (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(trans_size_we),
      .wd(trans_size_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.trans_size.q),

      // to register interface (read)
      .qs(trans_size_qs)
  );


  // R[curr_lvl]: V(False)

  prim_subreg #(
      .DW      (16),
      .SWACCESS("RW"),
      .RESVAL  (16'h0)
  ) u_curr_lvl (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(curr_lvl_we),
      .wd(curr_lvl_wd),

      // from internal hardware
      .de(hw2reg.curr_lvl.de),
      .d (hw2reg.curr_lvl.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.curr_lvl.q),

      // to register interface (read)
      .qs(curr_lvl_qs)
  );


  // R[hysteresis_en]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_hysteresis_en (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(hysteresis_en_we),
      .wd(hysteresis_en_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.hysteresis_en.q),

      // to register interface (read)
      .qs(hysteresis_en_qs)
  );


  // R[dlvl_log_level_width]: V(False)

  prim_subreg #(
      .DW      (4),
      .SWACCESS("RW"),
      .RESVAL  (4'h0)
  ) u_dlvl_log_level_width (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(dlvl_log_level_width_we),
      .wd(dlvl_log_level_width_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.dlvl_log_level_width.q),

      // to register interface (read)
      .qs(dlvl_log_level_width_qs)
  );


  // R[discard_bits]: V(False)

  prim_subreg #(
      .DW      (4),
      .SWACCESS("RW"),
      .RESVAL  (4'h0)
  ) u_discard_bits (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(discard_bits_we),
      .wd(discard_bits_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.discard_bits.q),

      // to register interface (read)
      .qs(discard_bits_qs)
  );


  // R[dlvl_n_bits]: V(False)

  prim_subreg #(
      .DW      (4),
      .SWACCESS("RW"),
      .RESVAL  (4'h0)
  ) u_dlvl_n_bits (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(dlvl_n_bits_we),
      .wd(dlvl_n_bits_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.dlvl_n_bits.q),

      // to register interface (read)
      .qs(dlvl_n_bits_qs)
  );


  // R[dlvl_mask]: V(False)

  prim_subreg #(
      .DW      (16),
      .SWACCESS("RW"),
      .RESVAL  (16'h0)
  ) u_dlvl_mask (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(dlvl_mask_we),
      .wd(dlvl_mask_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.dlvl_mask.q),

      // to register interface (read)
      .qs(dlvl_mask_qs)
  );


  // R[dlvl_format]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_dlvl_format (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(dlvl_format_we),
      .wd(dlvl_format_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.dlvl_format.q),

      // to register interface (read)
      .qs(dlvl_format_qs)
  );


  // R[dt_mask]: V(False)

  prim_subreg #(
      .DW      (16),
      .SWACCESS("RW"),
      .RESVAL  (16'h0)
  ) u_dt_mask (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(dt_mask_we),
      .wd(dt_mask_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.dt_mask.q),

      // to register interface (read)
      .qs(dt_mask_qs)
  );


  // R[bypass]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_bypass (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(bypass_we),
      .wd(bypass_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.bypass.q),

      // to register interface (read)
      .qs(bypass_qs)
  );




  logic [9:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == DLC_TRANS_SIZE_OFFSET);
    addr_hit[1] = (reg_addr == DLC_CURR_LVL_OFFSET);
    addr_hit[2] = (reg_addr == DLC_HYSTERESIS_EN_OFFSET);
    addr_hit[3] = (reg_addr == DLC_DLVL_LOG_LEVEL_WIDTH_OFFSET);
    addr_hit[4] = (reg_addr == DLC_DISCARD_BITS_OFFSET);
    addr_hit[5] = (reg_addr == DLC_DLVL_N_BITS_OFFSET);
    addr_hit[6] = (reg_addr == DLC_DLVL_MASK_OFFSET);
    addr_hit[7] = (reg_addr == DLC_DLVL_FORMAT_OFFSET);
    addr_hit[8] = (reg_addr == DLC_DT_MASK_OFFSET);
    addr_hit[9] = (reg_addr == DLC_BYPASS_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(DLC_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(DLC_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(DLC_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(DLC_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(DLC_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(DLC_PERMIT[5] & ~reg_be))) |
               (addr_hit[6] & (|(DLC_PERMIT[6] & ~reg_be))) |
               (addr_hit[7] & (|(DLC_PERMIT[7] & ~reg_be))) |
               (addr_hit[8] & (|(DLC_PERMIT[8] & ~reg_be))) |
               (addr_hit[9] & (|(DLC_PERMIT[9] & ~reg_be)))));
  end

  assign trans_size_we = addr_hit[0] & reg_we & !reg_error;
  assign trans_size_wd = reg_wdata[15:0];

  assign curr_lvl_we = addr_hit[1] & reg_we & !reg_error;
  assign curr_lvl_wd = reg_wdata[15:0];

  assign hysteresis_en_we = addr_hit[2] & reg_we & !reg_error;
  assign hysteresis_en_wd = reg_wdata[0];

  assign dlvl_log_level_width_we = addr_hit[3] & reg_we & !reg_error;
  assign dlvl_log_level_width_wd = reg_wdata[3:0];

  assign discard_bits_we = addr_hit[4] & reg_we & !reg_error;
  assign discard_bits_wd = reg_wdata[3:0];

  assign dlvl_n_bits_we = addr_hit[5] & reg_we & !reg_error;
  assign dlvl_n_bits_wd = reg_wdata[3:0];

  assign dlvl_mask_we = addr_hit[6] & reg_we & !reg_error;
  assign dlvl_mask_wd = reg_wdata[15:0];

  assign dlvl_format_we = addr_hit[7] & reg_we & !reg_error;
  assign dlvl_format_wd = reg_wdata[0];

  assign dt_mask_we = addr_hit[8] & reg_we & !reg_error;
  assign dt_mask_wd = reg_wdata[15:0];

  assign bypass_we = addr_hit[9] & reg_we & !reg_error;
  assign bypass_wd = reg_wdata[0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[15:0] = trans_size_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[15:0] = curr_lvl_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[0] = hysteresis_en_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[3:0] = dlvl_log_level_width_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[3:0] = discard_bits_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[3:0] = dlvl_n_bits_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[15:0] = dlvl_mask_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[0] = dlvl_format_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[15:0] = dt_mask_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[0] = bypass_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module dlc_reg_top_intf #(
    parameter  int AW = 6,
    localparam int DW = 32
) (
    input logic clk_i,
    input logic rst_ni,
    REG_BUS.in regbus_slave,
    // To HW
    output dlc_reg_pkg::dlc_reg2hw_t reg2hw,  // Write
    input dlc_reg_pkg::dlc_hw2reg_t hw2reg,  // Read
    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);
  localparam int unsigned STRB_WIDTH = DW / 8;

  `include "register_interface/typedef.svh"
  `include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;

  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)



  dlc_reg_top #(
      .reg_req_t(reg_bus_req_t),
      .reg_rsp_t(reg_bus_rsp_t),
      .AW(AW)
  ) i_regs (
      .clk_i,
      .rst_ni,
      .reg_req_i(s_reg_req),
      .reg_rsp_o(s_reg_rsp),
      .reg2hw,  // Write
      .hw2reg,  // Read
      .devmode_i
  );

endmodule


