// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package dlc_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 6;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {logic [15:0] q;} dlc_reg2hw_trans_size_reg_t;

  typedef struct packed {logic [15:0] q;} dlc_reg2hw_curr_lvl_reg_t;

  typedef struct packed {logic q;} dlc_reg2hw_hysteresis_en_reg_t;

  typedef struct packed {logic [3:0] q;} dlc_reg2hw_dlvl_log_level_width_reg_t;

  typedef struct packed {logic [3:0] q;} dlc_reg2hw_discard_bits_reg_t;

  typedef struct packed {logic [3:0] q;} dlc_reg2hw_dlvl_n_bits_reg_t;

  typedef struct packed {logic [15:0] q;} dlc_reg2hw_dlvl_mask_reg_t;

  typedef struct packed {logic q;} dlc_reg2hw_dlvl_format_reg_t;

  typedef struct packed {logic [15:0] q;} dlc_reg2hw_dt_mask_reg_t;

  typedef struct packed {logic q;} dlc_reg2hw_bypass_reg_t;

  typedef struct packed {
    logic [15:0] d;
    logic        de;
  } dlc_hw2reg_curr_lvl_reg_t;

  // Register -> HW type
  typedef struct packed {
    dlc_reg2hw_trans_size_reg_t trans_size;  // [78:63]
    dlc_reg2hw_curr_lvl_reg_t curr_lvl;  // [62:47]
    dlc_reg2hw_hysteresis_en_reg_t hysteresis_en;  // [46:46]
    dlc_reg2hw_dlvl_log_level_width_reg_t dlvl_log_level_width;  // [45:42]
    dlc_reg2hw_discard_bits_reg_t discard_bits;  // [41:38]
    dlc_reg2hw_dlvl_n_bits_reg_t dlvl_n_bits;  // [37:34]
    dlc_reg2hw_dlvl_mask_reg_t dlvl_mask;  // [33:18]
    dlc_reg2hw_dlvl_format_reg_t dlvl_format;  // [17:17]
    dlc_reg2hw_dt_mask_reg_t dt_mask;  // [16:1]
    dlc_reg2hw_bypass_reg_t bypass;  // [0:0]
  } dlc_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    dlc_hw2reg_curr_lvl_reg_t curr_lvl;  // [16:0]
  } dlc_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] DLC_TRANS_SIZE_OFFSET = 6'h0;
  parameter logic [BlockAw-1:0] DLC_CURR_LVL_OFFSET = 6'h4;
  parameter logic [BlockAw-1:0] DLC_HYSTERESIS_EN_OFFSET = 6'h8;
  parameter logic [BlockAw-1:0] DLC_DLVL_LOG_LEVEL_WIDTH_OFFSET = 6'hc;
  parameter logic [BlockAw-1:0] DLC_DISCARD_BITS_OFFSET = 6'h10;
  parameter logic [BlockAw-1:0] DLC_DLVL_N_BITS_OFFSET = 6'h14;
  parameter logic [BlockAw-1:0] DLC_DLVL_MASK_OFFSET = 6'h18;
  parameter logic [BlockAw-1:0] DLC_DLVL_FORMAT_OFFSET = 6'h1c;
  parameter logic [BlockAw-1:0] DLC_DT_MASK_OFFSET = 6'h20;
  parameter logic [BlockAw-1:0] DLC_BYPASS_OFFSET = 6'h24;

  // Register index
  typedef enum int {
    DLC_TRANS_SIZE,
    DLC_CURR_LVL,
    DLC_HYSTERESIS_EN,
    DLC_DLVL_LOG_LEVEL_WIDTH,
    DLC_DISCARD_BITS,
    DLC_DLVL_N_BITS,
    DLC_DLVL_MASK,
    DLC_DLVL_FORMAT,
    DLC_DT_MASK,
    DLC_BYPASS
  } dlc_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] DLC_PERMIT[10] = '{
      4'b0011,  // index[0] DLC_TRANS_SIZE
      4'b0011,  // index[1] DLC_CURR_LVL
      4'b0001,  // index[2] DLC_HYSTERESIS_EN
      4'b0001,  // index[3] DLC_DLVL_LOG_LEVEL_WIDTH
      4'b0001,  // index[4] DLC_DISCARD_BITS
      4'b0001,  // index[5] DLC_DLVL_N_BITS
      4'b0011,  // index[6] DLC_DLVL_MASK
      4'b0001,  // index[7] DLC_DLVL_FORMAT
      4'b0011,  // index[8] DLC_DT_MASK
      4'b0001  // index[9] DLC_BYPASS
  };

endpackage

