// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module fast_intr_ctrl_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 4
) (
    input logic clk_i,
    input logic rst_ni,
    input reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,
    // To HW
    output fast_intr_ctrl_reg_pkg::fast_intr_ctrl_reg2hw_t reg2hw,  // Write
    input fast_intr_ctrl_reg_pkg::fast_intr_ctrl_hw2reg_t hw2reg,  // Read


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import fast_intr_ctrl_reg_pkg::*;

  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [ AW-1:0] reg_addr;
  logic [ DW-1:0] reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [ DW-1:0] reg_rdata;
  logic           reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [14:0] fast_intr_pending_qs;
  logic [14:0] fast_intr_clear_qs;
  logic [14:0] fast_intr_clear_wd;
  logic fast_intr_clear_we;
  logic [14:0] fast_intr_enable_qs;
  logic [14:0] fast_intr_enable_wd;
  logic fast_intr_enable_we;

  // Register instances
  // R[fast_intr_pending]: V(False)

  prim_subreg #(
      .DW      (15),
      .SWACCESS("RO"),
      .RESVAL  (15'h0)
  ) u_fast_intr_pending (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.fast_intr_pending.de),
      .d (hw2reg.fast_intr_pending.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.fast_intr_pending.q),

      // to register interface (read)
      .qs(fast_intr_pending_qs)
  );


  // R[fast_intr_clear]: V(False)

  prim_subreg #(
      .DW      (15),
      .SWACCESS("RW"),
      .RESVAL  (15'h0)
  ) u_fast_intr_clear (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(fast_intr_clear_we),
      .wd(fast_intr_clear_wd),

      // from internal hardware
      .de(hw2reg.fast_intr_clear.de),
      .d (hw2reg.fast_intr_clear.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.fast_intr_clear.q),

      // to register interface (read)
      .qs(fast_intr_clear_qs)
  );


  // R[fast_intr_enable]: V(False)

  prim_subreg #(
      .DW      (15),
      .SWACCESS("RW"),
      .RESVAL  (15'h7fff)
  ) u_fast_intr_enable (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(fast_intr_enable_we),
      .wd(fast_intr_enable_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.fast_intr_enable.q),

      // to register interface (read)
      .qs(fast_intr_enable_qs)
  );




  logic [2:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == FAST_INTR_CTRL_FAST_INTR_PENDING_OFFSET);
    addr_hit[1] = (reg_addr == FAST_INTR_CTRL_FAST_INTR_CLEAR_OFFSET);
    addr_hit[2] = (reg_addr == FAST_INTR_CTRL_FAST_INTR_ENABLE_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(FAST_INTR_CTRL_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(FAST_INTR_CTRL_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(FAST_INTR_CTRL_PERMIT[2] & ~reg_be)))));
  end

  assign fast_intr_clear_we  = addr_hit[1] & reg_we & !reg_error;
  assign fast_intr_clear_wd  = reg_wdata[14:0];

  assign fast_intr_enable_we = addr_hit[2] & reg_we & !reg_error;
  assign fast_intr_enable_wd = reg_wdata[14:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[14:0] = fast_intr_pending_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[14:0] = fast_intr_clear_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[14:0] = fast_intr_enable_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule
