// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module my_ip_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 5
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output my_ip_reg_pkg::my_ip_reg2hw_t reg2hw, // Write
  input  my_ip_reg_pkg::my_ip_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import my_ip_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic intr_state_qs;
  logic intr_state_wd;
  logic intr_state_we;
  logic intr_enable_qs;
  logic intr_enable_wd;
  logic intr_enable_we;
  logic intr_test_wd;
  logic intr_test_we;
  logic control_start_qs;
  logic control_start_wd;
  logic control_start_we;
  logic control_write_qs;
  logic control_write_wd;
  logic control_write_we;
  logic [31:0] address_qs;
  logic [31:0] address_wd;
  logic address_we;
  logic [31:0] data_qs;
  logic [31:0] data_wd;
  logic data_we;
  logic [31:0] length_qs;
  logic [31:0] length_wd;
  logic length_we;

  // Register instances
  // R[intr_state]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("W1C"),
    .RESVAL  (1'h0)
  ) u_intr_state (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (intr_state_we),
    .wd     (intr_state_wd),

    // from internal hardware
    .de     (hw2reg.intr_state.de),
    .d      (hw2reg.intr_state.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.intr_state.q ),

    // to register interface (read)
    .qs     (intr_state_qs)
  );


  // R[intr_enable]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_intr_enable (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (intr_enable_we),
    .wd     (intr_enable_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.intr_enable.q ),

    // to register interface (read)
    .qs     (intr_enable_qs)
  );


  // R[intr_test]: V(True)

  prim_subreg_ext #(
    .DW    (1)
  ) u_intr_test (
    .re     (1'b0),
    .we     (intr_test_we),
    .wd     (intr_test_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.intr_test.qe),
    .q      (reg2hw.intr_test.q ),
    .qs     ()
  );


  // R[control]: V(False)

  //   F[start]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_control_start (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (control_start_we),
    .wd     (control_start_wd),

    // from internal hardware
    .de     (hw2reg.control.start.de),
    .d      (hw2reg.control.start.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.control.start.q ),

    // to register interface (read)
    .qs     (control_start_qs)
  );


  //   F[write]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_control_write (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (control_write_we),
    .wd     (control_write_wd),

    // from internal hardware
    .de     (hw2reg.control.write.de),
    .d      (hw2reg.control.write.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.control.write.q ),

    // to register interface (read)
    .qs     (control_write_qs)
  );


  // R[address]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_address (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (address_we),
    .wd     (address_wd),

    // from internal hardware
    .de     (hw2reg.address.de),
    .d      (hw2reg.address.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.address.q ),

    // to register interface (read)
    .qs     (address_qs)
  );


  // R[data]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_data (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (data_we),
    .wd     (data_wd),

    // from internal hardware
    .de     (hw2reg.data.de),
    .d      (hw2reg.data.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data.q ),

    // to register interface (read)
    .qs     (data_qs)
  );


  // R[length]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_length (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (length_we),
    .wd     (length_wd),

    // from internal hardware
    .de     (hw2reg.length.de),
    .d      (hw2reg.length.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.length.q ),

    // to register interface (read)
    .qs     (length_qs)
  );




  logic [6:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == MY_IP_INTR_STATE_OFFSET);
    addr_hit[1] = (reg_addr == MY_IP_INTR_ENABLE_OFFSET);
    addr_hit[2] = (reg_addr == MY_IP_INTR_TEST_OFFSET);
    addr_hit[3] = (reg_addr == MY_IP_CONTROL_OFFSET);
    addr_hit[4] = (reg_addr == MY_IP_ADDRESS_OFFSET);
    addr_hit[5] = (reg_addr == MY_IP_DATA_OFFSET);
    addr_hit[6] = (reg_addr == MY_IP_LENGTH_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(MY_IP_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(MY_IP_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(MY_IP_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(MY_IP_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(MY_IP_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(MY_IP_PERMIT[5] & ~reg_be))) |
               (addr_hit[6] & (|(MY_IP_PERMIT[6] & ~reg_be)))));
  end

  assign intr_state_we = addr_hit[0] & reg_we & !reg_error;
  assign intr_state_wd = reg_wdata[0];

  assign intr_enable_we = addr_hit[1] & reg_we & !reg_error;
  assign intr_enable_wd = reg_wdata[0];

  assign intr_test_we = addr_hit[2] & reg_we & !reg_error;
  assign intr_test_wd = reg_wdata[0];

  assign control_start_we = addr_hit[3] & reg_we & !reg_error;
  assign control_start_wd = reg_wdata[0];

  assign control_write_we = addr_hit[3] & reg_we & !reg_error;
  assign control_write_wd = reg_wdata[1];

  assign address_we = addr_hit[4] & reg_we & !reg_error;
  assign address_wd = reg_wdata[31:0];

  assign data_we = addr_hit[5] & reg_we & !reg_error;
  assign data_wd = reg_wdata[31:0];

  assign length_we = addr_hit[6] & reg_we & !reg_error;
  assign length_wd = reg_wdata[31:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = intr_state_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = intr_enable_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[0] = '0;
      end

      addr_hit[3]: begin
        reg_rdata_next[0] = control_start_qs;
        reg_rdata_next[1] = control_write_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = address_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = data_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[31:0] = length_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module my_ip_reg_top_intf
#(
  parameter int AW = 5,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output my_ip_reg_pkg::my_ip_reg2hw_t reg2hw, // Write
  input  my_ip_reg_pkg::my_ip_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  my_ip_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


