// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package i2s_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 4;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {logic [31:0] q;} i2s_reg2hw_outputdata_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } i2s_reg2hw_inputdata_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } i2s_hw2reg_outputdata_reg_t;

  // Register -> HW type
  typedef struct packed {
    i2s_reg2hw_outputdata_reg_t outputdata;  // [64:33]
    i2s_reg2hw_inputdata_reg_t  inputdata;   // [32:0]
  } i2s_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    i2s_hw2reg_outputdata_reg_t outputdata;  // [32:0]
  } i2s_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] I2S_OUTPUTDATA_OFFSET = 4'h0;
  parameter logic [BlockAw-1:0] I2S_INPUTDATA_OFFSET = 4'h4;

  // Window parameters
  parameter logic [BlockAw-1:0] I2S_RXDATA_OFFSET = 4'h8;
  parameter int unsigned I2S_RXDATA_SIZE = 'h4;

  // Register index
  typedef enum int {
    I2S_OUTPUTDATA,
    I2S_INPUTDATA
  } i2s_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] I2S_PERMIT[2] = '{
      4'b1111,  // index[0] I2S_OUTPUTDATA
      4'b1111  // index[1] I2S_INPUTDATA
  };

endpackage

