#!/usr/bin/env python

## Copyright 2024 EPFL
## Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
## SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1

import sys
import random
import numpy as np

def write_arr(f, name, arr, ctype, size):
    f.write("const " + ctype + " " + name + "[] = {\n")

    for row in arr:
        for elem in row[:-1]:
            f.write('%d,' % (elem))
        f.write('%d,\n' % (row[-1]))

    f.write('};\n\n')
    return


################################################################################
f = open('matrixMul8.h', 'w')
f.write('#ifndef _MATMUL8_\n')
f.write('#define _MATMUL8_\n')
f.write('// This file is automatically generated\n')


SIZE  = 16
RANGE = 4

m_a   = []
m_b   = []
m_exp = []

# Generate random 8 bit integers from -RANGE to RANGE for A and B
m_a = np.random.randint(-RANGE, RANGE, size=(SIZE, SIZE), dtype=np.int32)
m_b = np.random.randint(-RANGE, RANGE, size=(SIZE, SIZE), dtype=np.int32)
m_exp = np.zeros((SIZE, SIZE), dtype=np.int32)

# Test the function with A and B
m_exp = np.matmul(m_a,m_b)

write_arr(f, 'm_a',   m_a, 'int8_t', SIZE)
write_arr(f, 'm_b',   m_b, 'int8_t', SIZE)
write_arr(f, 'm_exp', m_exp, 'int32_t', SIZE)

f.write('#define SIZE %d\n' % SIZE)


f.write('#endif')
