// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package multi3x_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 3;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {logic [31:0] q;} multi3x_reg2hw_datain_reg_t;

  typedef struct packed {logic [31:0] q;} multi3x_reg2hw_dataout_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } multi3x_hw2reg_dataout_reg_t;

  // Register -> HW type
  typedef struct packed {
    multi3x_reg2hw_datain_reg_t  datain;   // [63:32]
    multi3x_reg2hw_dataout_reg_t dataout;  // [31:0]
  } multi3x_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    multi3x_hw2reg_dataout_reg_t dataout;  // [32:0]
  } multi3x_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] MULTI3X_DATAIN_OFFSET = 3'h0;
  parameter logic [BlockAw-1:0] MULTI3X_DATAOUT_OFFSET = 3'h4;

  // Register index
  typedef enum int {
    MULTI3X_DATAIN,
    MULTI3X_DATAOUT
  } multi3x_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] MULTI3X_PERMIT[2] = '{
      4'b1111,  // index[0] MULTI3X_DATAIN
      4'b1111  // index[1] MULTI3X_DATAOUT
  };

endpackage

