// File auto-generated by Padrick 0.3.1.post0.dev2+ge09286c
package pkg_internal_padframe_xheep;
  typedef struct packed {
    logic chip2pad;
    logic output_en;
  } mux_to_pad_pad_io_30_t;

  typedef struct packed {logic pad2chip;} pad_to_mux_pad_io_30_t;

  typedef struct packed {
    logic chip2pad;
    logic output_en;
  } mux_to_pad_pad_io_31_t;

  typedef struct packed {logic pad2chip;} pad_to_mux_pad_io_31_t;

  typedef struct packed {
    mux_to_pad_pad_io_30_t pad_io_30;
    mux_to_pad_pad_io_31_t pad_io_31;
  } mux_to_pads_t;

  typedef struct packed {
    pad_to_mux_pad_io_30_t pad_io_30;
    pad_to_mux_pad_io_31_t pad_io_31;
  } pads_to_mux_t;



  // Indices definitions

  parameter PAD_MUX_GROUP_PAD30_SEL_WIDTH = 2;
  parameter logic [1:0] PAD_MUX_GROUP_PAD30_SEL_DEFAULT = 2'd0;
  parameter logic [1:0] PAD_MUX_GROUP_PAD30_SEL_GPIO_GPIO_30 = 2'd1;
  parameter logic [1:0] PAD_MUX_GROUP_PAD30_SEL_I2C_I2C_SDA = 2'd2;

  parameter PAD_MUX_GROUP_PAD31_SEL_WIDTH = 2;
  parameter logic [1:0] PAD_MUX_GROUP_PAD31_SEL_DEFAULT = 2'd0;
  parameter logic [1:0] PAD_MUX_GROUP_PAD31_SEL_GPIO_GPIO_31 = 2'd1;
  parameter logic [1:0] PAD_MUX_GROUP_PAD31_SEL_I2C_I2C_SCL = 2'd2;

  // Dynamic Pad  instance index

  parameter PORT_MUX_GROUP_PAD30_SEL_WIDTH = 1;
  parameter logic [0:0] PORT_MUX_GROUP_PAD30_SEL_PAD_IO_30 = 1'd0;

  parameter PORT_MUX_GROUP_PAD31_SEL_WIDTH = 1;
  parameter logic [0:0] PORT_MUX_GROUP_PAD31_SEL_PAD_IO_31 = 1'd0;
endpackage : pkg_internal_padframe_xheep
