#!/bin/sh
# This script prints the welcome message upon login.

echo '  '
echo '   @@@@        @@@              @@@        @@@    @@@@@@@@@@@@@    @@@@@@@@@@@@@   @@@@@@@@@@     '
echo '   @@@@@     @@@@@              @@@        @@@    @@@@@@@@@@@@@@  @@@@@@@@@@@@@@   @@@@@@@@@@@@@  '
echo '     @@@@   @@@@@               @@@        @@@    @@@@            @@@@             @@@       @@@@ '
echo '      @@@@@@@@@                 @@@        @@@    @@@@            @@@@             @@@        @@@ '
echo '         @@@@@       @@@@@@@    @@@@@@@@@@@@@@    @@@@@@@@@@@@@   @@@@@@@@@@@@@    @@@       @@@@ '
echo '        @@@@@@      @@@@@@@@@   @@@@@@@@@@@@@@    @@@@@@@@@@@@@   @@@@@@@@@@@@@    @@@@@@@@@@@@@  '
echo '      @@@@@@@@@                 @@@        @@@    @@@@            @@@@             @@@@@@@@@@     '
echo '     @@@@   @@@@@               @@@        @@@    @@@@            @@@@             @@@            '
echo '   @@@@@      @@@@              @@@        @@@    @@@@@@@@@@@@@@  @@@@@@@@@@@@@@   @@@            '
echo '  @@@@         @@@@             @@@        @@@     @@@@@@@@@@@@    @@@@@@@@@@@@    @@@            '
echo '  '
echo '  '
echo '  Here is a quick start guide to run the "Hello, World!" example:'
echo '  1. Generate the RTL files: '
echo '          make mcu-gen'
echo '  2. Build the RTL simulation model: '
echo '          make verilator-build'
echo '  3. Build an example application to run: '
echo '          make app PROJECT=hello_world'
echo '  4. Run the RTL simulation: '
echo '          make verilator-run'
echo '  '
echo '  For more information, please visit: https://x-heep.readthedocs.io/en/latest/index.html'
echo '  '
echo '  Happy HEEPing! :)'
echo '  '