// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package iffifo_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 3;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [31:0] q;
    logic        re;
  } iffifo_reg2hw_fifo_out_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } iffifo_reg2hw_fifo_in_reg_t;

  typedef struct packed {logic [31:0] d;} iffifo_hw2reg_fifo_out_reg_t;

  // Register -> HW type
  typedef struct packed {
    iffifo_reg2hw_fifo_out_reg_t fifo_out;  // [65:33]
    iffifo_reg2hw_fifo_in_reg_t  fifo_in;   // [32:0]
  } iffifo_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    iffifo_hw2reg_fifo_out_reg_t fifo_out;  // [31:0]
  } iffifo_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] IFFIFO_FIFO_OUT_OFFSET = 3'h0;
  parameter logic [BlockAw-1:0] IFFIFO_FIFO_IN_OFFSET = 3'h4;

  // Reset values for hwext registers and their fields
  parameter logic [31:0] IFFIFO_FIFO_OUT_RESVAL = 32'h0;

  // Register index
  typedef enum int {
    IFFIFO_FIFO_OUT,
    IFFIFO_FIFO_IN
  } iffifo_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] IFFIFO_PERMIT[2] = '{
      4'b1111,  // index[0] IFFIFO_FIFO_OUT
      4'b1111  // index[1] IFFIFO_FIFO_IN
  };

endpackage

